export const MovieData = {
  title: "测试案例",
  createTime: 0,
  updateTime: 0,
  poster: "",
  width: 1920,
  height: 1080,
  background: {},
  transitions: [],
  cameras: [],
  captions: [],
  elements: [
    {
      id: "Pj3bSdJ16J",
      name: "bird_image_2.jpg",
      _dirty: "54iigz3jeb0000",
      type: "image",
      trackIndex: 1,
      resourceId: "ouo1moqgzs",
      startTime: 0,
      duration: 25,
      blendMode: 0,
      style: {
        width: 879.53,
        height: 586.96,
        x: 1480.21,
        y: 818.33,
        rotation: 0,
      },
      flipx: false,
      scale: 1,
      _ratio: 1.4979195561719834,
      filters: [],
      animates: [
        {
          id: "oRAfm5AC61",
          oid: "bounce",
          duration: 1,
          frames: [
            {
              progress: 0,
              transform: { translateY: 0 },
              id: "rksP-g7hE3",
              _dirty: "CDw5dhLM31",
            },
            {
              progress: 0.2,
              transform: { translateY: 0 },
              id: "p0nbthATK0",
              _dirty: "NcNNXsGl6N",
            },
            {
              progress: 0.4,
              transform: { translateY: -30 },
              id: "vJQRV2hBRL",
              _dirty: "vpHw5gPqRZ",
            },
            {
              progress: 0.43,
              transform: { translateY: -30 },
              id: "hS0myeLfP0",
              _dirty: "4klh5Ijdz8",
            },
            {
              progress: 0.53,
              transform: { translateY: 0 },
              id: "GYrHQvyUzE",
              _dirty: "JzOnL5ngm2",
            },
            {
              progress: 0.7,
              transform: { translateY: -15 },
              id: "McFV14AEj-",
              _dirty: "gXXc13Nmo9",
            },
            {
              progress: 0.8,
              transform: { translateY: 0 },
              id: "xyJu-wf_KE",
              _dirty: "Pc_ac-yKgA",
            },
            {
              progress: 0.9,
              transform: { translateY: -4 },
              id: "ATfB8Qujjd",
              _dirty: "0Qkb3JFjAk",
            },
            {
              progress: 1,
              transform: { translateY: 0 },
              id: "icyKA_sVtZ",
              _dirty: "LX6QX-2WQ4",
            },
          ],
          type: "emphasize",
          name: "bounce",
          ename: "bounce",
          start: 0,
          _dirty: "0",
          _animationDirty: "NmJRgPSj4C",
        },
      ],
      _animationDirty: "fV8pf-jUFT",
    },
    {
      id: "QyJG8xsDbU",
      name: "文字内容",
      text: "Core-SDK 是画布渲染部分的 SDK，\n传入工程数据（JSON）可以将数\n据绘制到 Canvas 上",
      textStyle: {
        radius: [0, 0, 0, 0],
        type: "newTextStyle",
        direction: "horizontal",
        fillType: "gradual",
        fill: {
          type: "linear",
          value: {
            angle: 1.5707963267948966,
            colors: [
              { color: "#bd10e0", offset: 0 },
              { color: "#50e3c2", offset: 1 },
            ],
          },
        },
        padding: [100, 100, 100, 100],
        fontSize: 200,
        letterSpacing: 9.92,
        lineHeight: 200,
        align: "center",
        fontFamily: "得意黑",
        stroke: {
          color: "rgb(111, 20, 190)",
          lineJoin: "round",
          lineWidth: 20,
        },
        fontFamilyURL: "/assets/fonts/得意黑.ttf",
      },
      style: { x: 937.28, y: 480.07, width: 1509.56, height: 416, rotation: 0 },
      _dirty: "1",
      type: "text",
      trackIndex: 2,
      startTime: 0,
      duration: 25,
      scale: 1,
      textScale: 0.52,
      textEnterAnimate: {
        id: "yt1W1HSAEJ",
        oid: "fadeInDown",
        type: "enter",
        name: "fadeInDown",
        ename: "fadeInDown",
        start: 0,
        duration: 1.5,
        frames: [
          {
            progress: 0,
            alpha: 0,
            transform: { translateY: -100 },
            id: "48OIjmuYWt",
            _dirty: "bByxn4pRZG",
          },
          {
            progress: 1,
            alpha: 1,
            transform: { translateY: 0 },
            id: "Pg4kkNgEZY",
            _dirty: "3EO0QAr0n-",
          },
        ],
        ease: "easeOutBounce",
      },
      _textStyleDirty: "yfD85yFmp6",
    },
    {
      id: "csyh88S5Lp",
      name: "Animation935",
      _dirty: "1",
      type: "lottie",
      trackIndex: 3,
      resourceId: "_9JNL-RFgM",
      startTime: 0,
      duration: 25,
      blendMode: 0,
      style: {
        width: 1426.76,
        height: 1426.76,
        x: 933.78,
        y: 513.78,
        rotation: 0,
      },
      lottieSpeed: 1,
      initStartFrame: 0,
      flipx: false,
      scale: 1,
      _ratio: 1,
      filters: [],
    },
    {
      id: "gcXRHGs1rS",
      name: "鸟类, 鸽子, 羽毛, 野生动物, 禽类, 鸟类学",
      _dirty: "1",
      type: "video",
      trackIndex: 4,
      resourceId: "HBn1RNZvg5",
      startTime: 0,
      matting: {
        enabled: false,
        color: "#008000",
        filterType: 0,
        lightLevel: 0.2,
        gridSize: 0.8,
      },
      duration: 25,
      muted: false,
      volume: 1,
      speed: 1,
      clipTime: 0,
      blendMode: 0,
      style: { width: 1920, height: 1080, x: 960, y: 540, rotation: 0 },
      flipx: false,
      scale: 1,
      _ratio: 1.7777777777777777,
      filters: [],
      textScale: 1,
    },
    {
      id: "_Nd0u9BEtR",
      name: "mixkit-a-very-happy-christmas-897.mp3",
      _dirty: "1",
      _noControl: true,
      type: "audio",
      trackIndex: 5,
      resourceId: "nKdEiA1wit",
      startTime: 0,
      duration: 25,
      muted: false,
      volume: 1,
      speed: 1,
      curveSpeed: false,
      clipTime: 0,
      fadeInTime: 0,
      fadeOutTime: 0,
    },
  ],
  resouces: [
    {
      id: "HBn1RNZvg5",
      name: "鸟类, 鸽子, 羽毛, 野生动物, 禽类, 鸟类学",
      type: "video",
      url: "/video/materials/videos/176933.mp4",
      originId: "656397618388500480",
      thumb: "/video/materials/videos/176933_thumb.png",
      styleSize: { width: 1920, height: 1080 },
      frames: "/video/uploads/20231209/657651681056432128.png",
      noAudioTracks: true,
      fileType: "video",
      from: "system",
      mustFetch: false,
      duration: 25,
      attrs: {
        width: 1920,
        frames: "/video/uploads/20231209/657651681056432128.png",
        height: 1080,
        duration: 25,
      },
    },
    {
      id: "nKdEiA1wit",
      name: "mixkit-a-very-happy-christmas-897.mp3",
      type: "audio",
      url: "/video/uploads/20250226/819207911986483200.mp3",
      originId: "819207918366019584",
      thumb: "/video/uploads/20250226/819207911986483200.mp3",
      styleSize: { width: null, height: null },
      wave: "/video/uploads/20250226/819207915629821952.json",
      noAudioTracks: false,
      fileType: "audio",
      from: "system",
      mustFetch: false,
      duration: 130.115918,
      attrs: {
        size: 4164589,
        wave: "/video/uploads/20250226/819207915629821952.json",
        duration: 130.115918,
      },
    },
    {
      id: "ouo1moqgzs",
      name: "aimatting_5r525jvmgr8000.png",
      type: "image",
      url: "/video/uploads/9715/20250520/849201261833322496.png",
      originId: "849201263280357376",
      thumb: "/video/uploads/9715/20250520/849201262629376000.png",
      styleSize: { width: 1080, height: 721 },
      fileType: "image",
      from: "user",
      mustFetch: true,
      attrs: { naturalWidth: 1080, naturalHeight: 721 },
    },
    {
      id: "_9JNL-RFgM",
      name: "Animation935",
      type: "lottie",
      url: "/video/uploads/20250403/832183369927938048.lottie",
      originId: "832183466752499712",
      thumb: "/video/uploads/20250403/832183459307610112.png",
      styleSize: { width: 800, height: 800 },
      fileType: "lottie",
      from: "system",
      mustFetch: true,
      duration: 3.03,
      extend: { width: 800, height: 800, frameRate: 30, totalFrames: 91 },
    },
  ],
  version: "1.1.0",
  _hideLock: {
    1: { hide: false, lock: false },
    2: { hide: false, lock: false },
    3: { hide: false, lock: false },
    4: { hide: false, lock: false },
    5: { hide: false, lock: false },
    6: { hide: false, lock: false },
    0.5: { hide: false, lock: false },
    0.25: { hide: false, lock: false },
    0.75: { hide: false, lock: false },
    0.125: { hide: false, lock: false },
    0.0625: { hide: false, lock: false },
    4.5: { hide: false, lock: false },
  },
};
